name: firebase_database_collection
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/fluttercommunity/firebase_flutter_sdk/tree/master/firebase_database_collection
author: long1eu <home@long1.eu>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
  dart_quickcheck:
    git: https://github.com/long1eu/dart_quickcheck.git